services:
  db:
    image: postgres:14-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB = "${POSTGRES_DB}"
      - POSTGRES_USER = "${POSTGRES_USER}"
      - POSTGRES_PASSWORD = "${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"

  backend:
    build: .
    command: bash -c "
      python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000
      "
    restart: on-failure
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db