# Generated by Django 4.1.3 on 2022-11-11 03:13

import ckeditor.fields
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=250)),
                ("image", models.ImageField(upload_to="categories")),
                ("description", ckeditor.fields.RichTextField()),
                ("slug", models.SlugField(unique=True)),
            ],
            options={"verbose_name_plural": "Categories", "db_table": "categories",},
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=250)),
                ("image", models.ImageField(upload_to="tags")),
                ("description", ckeditor.fields.RichTextField()),
                ("slug", models.SlugField(unique=True)),
            ],
            options={"verbose_name_plural": "Tags", "db_table": "tags",},
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=250)),
                ("image", models.ImageField(upload_to="posts")),
                ("description", models.TextField()),
                ("is_published", models.BooleanField(default=True)),
                ("content", ckeditor_uploader.fields.RichTextUploadingField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("tags", models.ManyToManyField(to="posts.tag")),
            ],
            options={"verbose_name_plural": "Posts", "db_table": "posts",},
            managers=[("published", django.db.models.manager.Manager()),],
        ),
    ]
