# Generated by Django 4.1.3 on 2022-11-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(default="a", unique=True),
            preserve_default=False,
        ),
    ]
